name: example01
on:
    push:
        branches:
            - '!main'
    workflow_dispatch:
jobs:
    exam-01:
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: echo "test ${{ github.event_name }}"