name: example04
on: [workflow_dispatch]
jobs:
#parallel jobs
    Test1: 
        runs-on: ubuntu-latest
        steps:
            - run: "The job was automcatilly ${{ github.event_name }} "
    Test2: 
        runs-on: ubuntu-latest
        steps:
            - run: "The job was automcatilly ${{ github.event_name }}"   
    Test3:
        runs-on:  ubuntu-latest
        steps:
            - run: "The job was automactilaly ${{ github.event_name }}"