name: example02
on:
    workflow_dispatch:
        inputs:
            loglevel:
                description: 'Log level'
                required: true
                default: 'warning'
                type: choice
                options:
                    - info
                    - warning
                    - debug
            print_tags:
                description: 'True or Flase'
                required: true
                type: boolean
            tags:
                description: 'Test tags'
                required: true
                type: string
            env:
                description: 'Env to run against'
                type: environment 
                required: true

jobs:
    explore-jobs:
        runs-on: ubuntu-latest
        steps:
            - run: "The job$ ${{inputs.tags}} ${{ inputs.env }} ${{inputs.loglevel}} ${{inputs.print_tags}}"