name: example07a
on:
    workflow_dispatch
jobs:
    Test1:
        runs-on: ubuntu-latest
        steps:
            - run: |
                # exit 1
                echo Intentional >> $GITHUB_STEP_SUMMARY
                echo "Test=test" >> $GITHUB_OUTPUT