name: Github actions demo
on: [workflow_dispatch]
jobs:
  Explore-Github-actions:
    runs-on: self-hosted
    steps:
      - run: echo "hello"
      - name: list
        run: |
          echo $PATH
          ls ${{ github.workspace }}